### ISSUE TITLE
LazyLoadListView getting via refs gives errors

### ISSUE THREAD

**Issue by waleedarshad-vf** [magicismight/react-native-lazyload#16]
this.refs.listview.scrollProperties undefined? It does not respond much properties like scrollProperties

**Comment by magicismight** [comment]
fixed in 1.1.0

**Comment by waleedarshad-vf** [comment]
I am using "react-native-lazyload": "^1.0.4"

**Comment by magicismight** [comment]
The fix is inside 1.1.0 which is just released few minutes ago.
