### ISSUE TITLE
"host" property throws exception

### ISSUE THREAD

**Issue by Amurmurmur** [magicismight/react-native-lazyload#18]
When passing host=nameofthelistview react throws such error:
![simulator screen shot 16 sep 2016 22 56 54](https://cloud.githubusercontent.com/assets/8608333/18602419/df70c9d0-7c60-11e6-910f-c7f8f2e5a419.png)

using as such:

```
<LazyloadListView
      name="lazy-load-listview"
      stickyHeaderIndices={[0]}
      renderDistance={100}
      pageSize={1}
      enableEmptySections={true}
      initialListSize={10}
      scrollRenderAheadDistance={50}
      automaticallyAdjustContentInsets={true}
      dataSource={dataSource}
      renderRow={this._renderRow}
      contentContainerStyle={AppStyles.paddingBottom}
      style={{backgroundColor: 'transparent'}}
      refreshControl={
        <RefreshControl
          refreshing={this.props.isFetching}
          onRefresh={this._fetchData}
          style={{backgroundColor: 'transparent'}}
          tintColor={AppConfig.primaryColor} />
      }
      />

```

and in renderRow:

```
_renderRow = (data) => {
    let { name, image_link } = data;
       return (
        <RowComponent
          title={name}
          image={image_link}
          onPress={()=>{
            Actions.anotherView()
          }}>
        </RowComponent>
    );
  }
```

and in the RowComponent:
  `<LazyloadImage source={{uri: image}} style={styles.imageBackground_image} host="lazy-load-listview">`

**Comment by magicismight** [comment]
It seems like the `LazyloadImage` elements are not the descendants of `LazyloadListView` which  has the `name` prop same as the `host` prop.

please make sure each `LazyloadListView` element has a unique name.

**Comment by Amurmurmur** [comment]
Yep that solved the problem, it works.
However, LazyLoadListViews still eat a lot of RAM :/
