### ISSUE TITLE
How can I add a placeholder image for the lazyloaded ?

### ISSUE THREAD

**Issue by shidhincr** [magicismight/react-native-lazyload#3]

**Comment by magicismight** [comment]
You can add a placeholder image like this:

``` js
<LazyloadScrollView name="some-scrollview">
...other elements

<Image
    style={/*image container style*/}
    source={/*placeholder source*/}
>
    <LazyloadView host="some-scrollview">
        <Image
            source={/*origin image source*/} 
        />
    </LazyloadScrollView>
</Image>

...other elements
</LazyloadScrollView>
```

**Comment by shidhincr** [comment]
Thanks @magicismight .. Lemme try that

**Comment by shidhincr** [comment]
Unfortunately this is kind of affecting the whole layout.. I am not able to use an image without the width ( because the placeholder  image is small ), but when I do that the whole layout will break.

Wdyt ?

**Comment by magicismight** [comment]
you can set the same width and height for placeholder image and the content inside it.
This won't break the layout after LazyloadView is loaded.

**Comment by magicismight** [comment]
For example

``` js
<Image
  style={width:100,height:100}
  source={placeholder source}
>
  <LazyloadImage
    host="some host"
    style={width:100,height:100}
    source={origin img source}
  />
</Image>

```

after the LazyloadImage is loaded, it will cover the placeholder

**Comment by magicismight** [comment]
If you want to use small placeholder.
you can use View instead of image.

``` js
<View
    style={width:100,height:100,position:"relative",backgroundColor:"red"}
>
  <Image
    style={position:"absolute", width: 10,height:10,left:45,top:45}
    source={placeholder source}
  />
  <LazyloadImage
    host="some host"
    style={position:"absolute",top:0,left:0,width:100,height:100}
    source={origin img source}
  />

</View>

```

**Comment by magicismight** [comment]
I`m using those kind of solutions in my project.
Everthing works fine for me.

**Comment by shidhincr** [comment]
@magicismight Thanks a lot for the detailed examples.. I'll try these..
