### ISSUE TITLE
cannot read property 'shape' of undefined

### ISSUE THREAD

**Issue by guopeng1994** [magicismight/react-native-lazyload#37]
when i import this library in my js file, it happend. 
plat: android 6.0
RN:0.47.0
react-native-lazyload:1.1.0

**Comment by frameworktechnology** [comment]
I am facing the same issue. 
 "react-native": "0.49.5",
"react-native-lazyload": "^1.1.0",
Please help. Thanks

**Comment by al-wi** [comment]
PropTypes have been removed from react.
Here the PR https://github.com/magicismight/react-native-lazyload/pull/34
And an alternate repo with this fix: https://github.com/soldotno/react-native-lazyload-deux

**Comment by tuantvk** [comment]
@guopeng1994 i same issue, but i fix it use `import PropTypes from 'prop-types'` and it working
