### ISSUE TITLE
get this Warning: ScrollView doesn't take rejection well - scrolls anyway

### ISSUE THREAD

**Issue by ronaldx** [magicismight/react-native-lazyload#4]
Hi, I get this warning "get this Warning: ScrollView doesn't take rejection well - scrolls anyway" when setting the LazyloadScrollView as horizontal={true}. Please Help.

**Comment by ronaldx** [comment]
it seems this has to do with https://github.com/facebook/react-native/issues/1501

**Comment by magicismight** [comment]
I`m closing this, beacause react-native had removed this warning in 0.24.0
