### ISSUE TITLE
Touchable child must either be native or forward setNativeProps to a native component

### ISSUE THREAD

**Issue by ucoker** [magicismight/react-native-lazyload#7]
code:
- If I put LazyloadView under the TouchableHighlight,Debugger will throw the error  
  `Unhandled JS Exception: Touchable child must either be native or forward setNativeProps to a native component`  
  **My Code:**

``` js
<TouchableHighlight
  style={{flex:1}}
  onPress={this._onPressRow.bind(this, element, sectionID, rowID)}>
  <LazyloadView
        host="feature_detail_LazyloadListView"
        style={[styles.row,{height: height}]}>
   <Text>Some Text</Text>
   </LazyloadView>
</TouchableHighlight>
```

![qq20160519-0](https://cloud.githubusercontent.com/assets/12216739/15368733/e0181ac2-1d61-11e6-9924-55fa48096a1f.png)

How to fix it ?

Thanks

**Comment by magicismight** [comment]
I`ll fix this later.
Thanks for reporting this

**Comment by ucoker** [comment]
You are welcome.
